### ISSUE TITLE
API KEY

### ISSUE THREAD

**Issue by ispeh** [poppy792/YouTube_konstrukcijske#1]
Kreirati API KEY za korištenje YouTube DataApi-ja. Primjer kako napraviti ApiKey:
https://www.youtube.com/watch?v=-UCHsqxBqwY

**Comment by poppy792** [comment]
https://www.youtube.com/watch?v=_HYYJelTExE

Noviji primjer kreiranja API key-a. Sa 2016 se ne poklapa kreiranje, meni barem ja sam ga na ovaj način napravila.

**Comment by ispeh** [comment]
Ok, zatvaramo
